# Generated by Django 2.2.14 on 2021-12-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingman',
            name='adhar_card',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workingman',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workingman',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='workingman',
            name='phone2',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
