# Generated by Django 2.2.14 on 2021-12-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_contact', '0002_auto_20211222_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingman',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
