# Generated by Django 2.2.14 on 2021-12-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='pub_date',
        ),
    ]
