# Generated by Django 2.2.14 on 2021-12-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_service_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='product_name',
            new_name='service_name',
        ),
    ]
