# Generated by Django 2.2.14 on 2021-12-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20211215_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=300, null=True)),
                ('number', models.IntegerField()),
                ('locality', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
            ],
        ),
    ]
