# Generated by Django 2.2.14 on 2021-12-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
