# Generated by Django 2.2.14 on 2021-12-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_orders_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
