# Generated by Django 2.2.14 on 2021-12-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_workers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='order_id',
            new_name='id',
        ),
    ]
