# Generated by Django 2.2.14 on 2021-12-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20211216_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='phone2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
