# Generated by Django 2.2.14 on 2021-12-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_auto_20211216_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('1', 'Order Placed'), ('2', 'Order Confirmed'), ('3', 'Order Done'), ('4', 'Order Cancelled')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
